services:
  # 1. The PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notification_db
    ports:
      - "5432:5432"

  # 2. The Redis Message Broker & Cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 3. The FastAPI Web Server
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/notification_db
      - REDIS_URL=redis://redis:6379/0

  # 4. The Celery Background Worker
  worker:
    build: .
    command: celery -A worker.celery_app worker --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/notification_db
      - REDIS_URL=redis://redis:6379/0