apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-api
  template:
    metadata:
      labels:
        app: notification-api
    spec:
      containers:
      - name: api
        image: notification-service-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://admin:password@db-service:5432/notification_db"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-api-service
spec:
  selector:
    app: notification-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer